### ISSUE TITLE
Add support for Mercurial SCM

### ISSUE THREAD

**Issue by brejoc** [gogs/gogs#125]
Since the name of the project is Go Git Service this might be totally off limits, but support for Mercurial would be super awesome! The situation for Mercurial is even worse that git. With Rhodecode the only good self hosted hg service went commercial and moved all the source code to a proprietary license. Publishing hg repositories with hgweb is possible but scales not past 5 to 10 bigger repositories. Using SSH gives a much better performance, but is hard to maintain. So please add support for the SCM Go uses itself.

**Comment by StrangeWill** [comment]
Just pitching additional interest here. I could win a lot of people over to Gogs with Mecurial support. Our only solution in the market right now is RhodeCode (that went to a really expensive licensing model, more than GitHub for a self-hosted solution, and that takes effort) or we have to go with cloud-hosted solutions.

**Comment by lunny** [comment]
Mercurial SCM supports really need many efforts. But currently, gogs should pay attention to git functions  such as PR.

**Comment by brejoc** [comment]
@StrangeWill  In the meantime you can take a look at [Kallithea](https://kallithea-scm.org/). Kallithea is a fork of RhodeCode and, according to the mailing list, rather active. So this might be a good alternative if you want to stick to Mercurial.

**Comment by StrangeWill** [comment]
@brejoc Definately have Kallithea on the list for a solution where I can't move to Git, but on my personal repos I'm seriously moving to Git over having Gogs because it's a better platform for what i want to do even if I do lose Mercurial support. The thing is RhodeCode has never been that fast either, so unless the fork is highly optimized, meh on that front :(

@lunny  Agreed, pull request functionality is a big one (and stuff like code signing support would be nice, not even GitHub appears to have that), just keeping Mercurial support somewhere on the radar I think is a good idea (assuming implementation isn't a nightmare).

**Comment by sirinath** [comment]
It will be good to have Hg support also.

**Comment by jrmiller82** [comment]
+1 for Hg support also. I think you get quite a bit of donations for adding it, considering that you would be in the same realm as bitbucket.

**Comment by phonicmouse** [comment]
+1
