### ISSUE TITLE
is it stable to be deployed  in production env?

### ISSUE THREAD

**Issue by laofo** [gogs/gogs#37]
I mean to deploy in a company. how many company/people use gogs at present?

Is gogs released with BSD license?

Thanks.

**Comment by hickscorp** [comment]
On 10 of march 2015, IMO Gogs is for personnal use only. If you're really serious about professional usage, here are the two key points that made me avoid Gogs for team based corporate projects:

- Pull requests.
- Feedback from CI.

Also, many bugs have rencently been solved regarding security (Cross site scripting, daemon running as root etc). IMO those points were the tip of the iceberg, but are also very encouraging because there were solved very fast (Which proves that the developers are in fact very active on the project).

As of today, i consider Gogs a very handy way to collaborate with small teams, composed of individual who _must_ have a good git knowledge. I would not recommend using Gogs to people with poor / no knowledge of git, because they will find themselves stuck when the time of merging / reviewing conflicts comes.

When you're serious about collaboration, PRs play an essential role on the development cycle. We either ask contractors to fork our repo and issue PRs to us, or give write access to our in-house developers but give them the directive to not merge and do self-PRs for the first weeks of our collaboration, so we make sure they understand the cycle before going on their own.

CI feedback also plays a key role in our dev cycle. Our PRs reviewer has to be able to see the state of the code that is being PR'ed to our codebase without having to run the unit tests himself. The CI integration is a very nice way to see the health of a given branch inline within your SCM repository.

My recommendation would be to keep a bookmark on Gogs, because IMO it has a very bright future, and is going forward so quickly that i wouldn't be surprised to see all the features i want being implemented soon soon!

**Comment by hickscorp** [comment]
@compressed As you are mentioning that you would like Strider to pick up your Gogs pushes, please read this issue, as i describe the whole process of doing so. I am myself running many projects through Gogs, itself issuing a hook to Strider via a *git hook*.

See https://github.com/gogits/gogs/issues/813 and https://github.com/gogits/gogs/issues/793 .

**Comment by compressed** [comment]
@hickscorp thanks!

I actually ended up switching from strider to drone for CI. I liked the docker-based nature of drone. May be worth a shot if you want to try another option. There's integration between drone and gogs as well.
