### ISSUE TITLE
only Quick Guide is shown, instead of source files

### ISSUE THREAD

**Issue by sallespro** [gogs/gogs#418]
you create a repository, commits code, it works fine, but when you try to visualize the sources, it shows only the `Quick Guide`.

**Comment by voxxit** [comment]
I actually still see this being an issue. I am using version 0.5.16.0301 Beta.

Steps to reproduce:

1. Create a new [not migrated] private repository.
2. Push code to it

**Expected result:**
The source code/repository home page should show a directory structure of the repository, etc.

**Actual result:**
The "quick guide" showing how to commit/push to the repository is still shown.

I would like to note that, as with @sallespro, the code is actually pushed to the repository because I can clone it on the server locally, etc. but the web UI is not updated.

**Comment by Unknwon** [comment]
@voxxit this happens with your update hooks isn't correct, try regenerate all of them in admin dashboard(one click).

**Comment by GaryHost** [comment]
Hello,

I'm having the same issue, and regenerating the update hooks doesn't change it.
The code has been pushed, as I can pull it elsewhere, but the UI still shows the quick guide.

I'm using  0.6.1.0325 Beta, on Ubuntu 14.04 64 bits.

**Comment by seiichiro0185** [comment]
Hi,

it's the same behaviour for me, new installation (version 0.6.0.0319 Beta) on ArchLinux, created a new repo, and pushed existing code to it. Code is there in the acutal repository on disk, but the web UI only shows the quick guide. Even with the steps creating repo -> regenerate update hooks -> push code only the quick guide is visible in the UI.

**Comment by seiichiro0185** [comment]
Update for those affected: I found the Issue (at least on my server):

The /srv directory, where my repos are located, is a separate partition, which was mounted with the **noexec** flag, preventing any programs to be run from there. This also prevented the update hook from running, and so the UI never got updated.. Remounting the /srv partition without the noexec-flag did the trick, and everything is working as it should

**Comment by GaryHost** [comment]
That's weird because for me, gogs is installed under /opt, /opt/gogs belongs to the gogs user, and the repos are located under /home/gogs, also belonging to gogs.

**Comment by seiichiro0185** [comment]
Since we are on different distros the paths might be different, because these can be changend while packaging gogs. Did you check if /home is a separate partition on your server, and if so which mount-flags where used for it?

**Comment by GaryHost** [comment]
Nope, just one partition... I can run the update hook manually, logged in as the gogs user.
