### ISSUE TITLE
Web editor doesn't execute hooks after commit

### ISSUE THREAD

**Issue by Unknwon** [gogs/gogs#4338]
#### Affect

Since 0.10.0

#### Cause

Remote address of server local copy of repositories (for web editor and PR) is server file path, the entire push process is not delegated by Gogs. Therefore can't set needed environment variables (e.g. `GOGS_REPO_NAME`, etc.) then call hooks (`pre-receive`, `update`, `post-receive`).

#### Result

Even though commits push event is [simulated](https://github.com/gogits/gogs/blob/master/models/repo_editor.go#L156-L167), but Git hooks are not executed. 

Some side effects including:

1. Custom Git hooks are not executed
2. Repository size is not updated
3. ~~Pull request retest is not performed~~

#### Possible solution

Also simulate behavior of `pre-receive`, `update`, `post-receive`.

**Comment by dalareo** [comment]
Any news @Unknwon ?

**Comment by maethor** [comment]
Any news?

**Comment by Unknwon** [comment]
@maethor currently no updates, but will work on it soon.

**Comment by maethor** [comment]
Thank you! :)

**Comment by davidwinterstein** [comment]
Heyho, what's the status on this one?

**Comment by Unknwon** [comment]
On the roadmap to the next release but not immediately work on it.

**Comment by davidwinterstein** [comment]
Thanks, I'd really appreciate this feature. :smiley:

**Comment by CRCinAU** [comment]
A recent gogs convertee - but just wondering if there is any news on this?

Seems to have been outstanding for over a year now :(

**Comment by Unknwon** [comment]
Patch has pushed to fix this issue, please test on `develop` branch.

**Comment by esteban-turnocheck** [comment]
Hi! I'll comment on this issue since what's happening to me seems to be very related, at least in the behaviour.
I have a script very similar to https://discuss.gogs.io/t/how-to-work-a-git-hook/998, which originated this issue.
I know there are many variables involved, but for the sake of clarity I'll try to explain the problem first and fill in the data that could appear relevant when somebody think it is.
The script has a line in which I need to run a command as another user. Not root, but the owner of a series of files that make up my development web site. I've created a post-receive hook that simply checks-out the 'develop' branch on the webroot each time I push on 'develop'. Had it working for over a year (in a CentOS 6.5 VPS), but now I'm moving to a different host (Ubuntu 18.04), and there is no way it works.
When I run the script as user `git` (the user under which gogs and git runs), it works perfectly (I cut the script so it only does a basic thing, so to reproduce the error with the less possible clutter). The user `git` doesn't have permission for accesing the directories on the webroot, but the line `sudo -E -u tcpanel1 cd /home/tcpanel1/public_html/desarrollo` work as expected (the user `tcpanel1` has that access allowed so the cd gets executed)
But when I make a push, and the script is run by gogs (with user `git`), it gives back the error:
`sudo: effective uid is not 0, is /usr/bin/sudo on a file system with the 'nosuid' option set or an NFS file system without root privileges?`
I've been searching all weekend and already checked with mount to see if there is something which has the "noexec" bit or so. Nothing.
The user `git` is in the sudoers: 
`git     ALL=(tcpanel1:tcpanel)  NOPASSWD:ALL`

The most dazzling thing is that it works perfectly when I run it from a ssh terminal as user `git`

I hope somebody can help me since I'm lost since three days ago! Thank's!!!
