### ISSUE TITLE
Odd sorting of tags / releases if number of tags exceeds a particular value and pagination is added

### ISSUE THREAD

**Issue by rudeks** [gogs/gogs#4482]
- Gogs version (or commit ref): 0.11.6.0407 (Docker-Image)
- Git version: 2.11.1
- Operating system: Docker Image: `Linux <hostname> 4.6.0-0.bpo.1-amd64 #1 SMP Debian 4.6.1-1~bpo8+1 (2016-06-14) x86_64 Linux`
- Database:
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [x] Yes [try.gogs.io/rudeks](https://try.gogs.io/rudeks/testrepository-broken)
  - [ ] No
  - [ ] Not relevant
- Log [loglog.txt](https://github.com/gogits/gogs/files/975876/loglog.txt):

## Description

I encountered a problem recently, where tag sorting appears to be broken, as soon as pagination is added in the /releases view for a project. Unless a particular number of tags is reached, everything is fine and the tags appear in the right order. After reaching a particular number of tags is reached, newer Tags appear on later pages.

This occurs mainly when you `git push --tags` your local repository with tags that and if at least one tag resembles a name that does not follow the format of other tags. In the sample repository provided, you will find 25 tags that follow the form `v-[0..24].0.0` and two tags that do not follow the form, but, however, were created subsequently after `v-25.0.0_Reproduzierbarkeit`. One of these tags (that one, that is named `Noch-ein-Test-der-Reproduzierbarkeit` and does not follow the form at all) appears somewhere at the end of the *Tags* and *Releases*-List; in the `/releases`-resource the get param `?after=v-6.0.0` is appended to the URI. On this page the `Noch-ein-Test-der-Reproduzierbarkeit`-Tag shows up.

### Expected behavior

As the tag `v-25.0.0_Reproduzierbarkeit` was created right after `v-24.0.0`, and `Noch-ein-Test-der-Reproduzierbarkeit` was created after `v-25.0.0_Reproduzierbarkeit`, one expects that `Noch-ein-Test-der-Reproduzierbarkeit` appears after (or before, depending of the sorting) the tag created chronologically before.

**Comment by Unknwon** [comment]
You're right, shouldn't use `refname`([code](https://github.com/gogits/git-module/blob/master/repo_tag.go#L99)) as sort key but `taggerdate`.

**Comment by asedge** [comment]
I created a PR to fix this.  If more work is needed just let me know, thanks!

**Comment by Unknwon** [comment]
This is claimed to be fixed by merging https://github.com/gogs/git-module/pull/36, please help test on `develop` branch.

**Comment by AlgyTaylor** [comment]
Not sure this is fixed, I have a very strange release sort order on 0.11.66.0916

**Comment by Unknwon** [comment]
@AlgyTaylor Please define "strange" and try to reproduce on https://try.gogs.io

**Comment by AlgyTaylor** [comment]
@Unknwon - thanks for the reply, and also for writing Gogs - it's a really useful bit of software and I recommend it to **a lot** of people.   **(Screenshots below)**

Anyway, on the "releases" page, the first page shows releases from over a year ago.  I go on to page 2, and it shows some releases that have happened *since* the first entry on page 1, and also some duplicate entries from that page.  I've attached 2 screenshots of those pages below so you can see.  I add a release roughly once a week, so it should show v1.10.0, v1.9.5, v1.9.4, v1.9.3, ...

I'll try to recreate it now

This is the first page of my 'releases' page ... 
![fadf52c6-36be-42c9-8044-01aef299e781](https://user-images.githubusercontent.com/1220211/47006507-f4776900-d12d-11e8-8606-68cc4859f9a2.png)

... and here is page 2 ...

![d10dd0a3-49cc-48ff-ba53-088f81b78d75](https://user-images.githubusercontent.com/1220211/47006633-43250300-d12e-11e8-9d8d-fcaf589cdc09.png)

**Comment by Unknwon** [comment]
@AlgyTaylor thanks for the screenshot! If it could be reproduced on demo site, would be very helpful to solve the problem!

**Comment by AlgyTaylor** [comment]
Just a quick note to say this seems to have been fixed in the last 2/3 releases - thanks :) :+1:
