### ISSUE TITLE
Proposal: CC0 should be replaced with the The Unlicense

### ISSUE THREAD

**Issue by mogical** [gogs/gogs#4687]
Although CC0 is GPL-compatible and acceptable for software, CC&nbsp;licenses are recommended against to be used with softwares. It would be better if CC0 is replaced with [The&nbsp;Unlicense](http://unlicense.org), which is a more proper public&nbsp;domain dedication for softwares.

**Comment by cubiclesoft** [comment]
This is a wrong recommendation.  I had an extensive discussion on the Open Source Initiative (OSI) mailing list for license approvals not long ago where I submitted a MIT-style license that was similar to Unlicense but more succinct and probably more legally sufficient.  I retracted the license from proceeding forward through the process to save everyone time and decided CC0 is the closest you can get to public domain for written works (e.g. documentation) and that MIT is the closest anyone can currently get for software.  To summarize the discussion:  The problem is defining what "Public Domain" means while simultaneously affording the limited liability protections granted by MIT.  CC0 goes to great lengths to define it and a court can simply ignore whatever portions do not apply.  CC0 also falls back to a position of copyright, which is valid through jurisdictions that won't recognize public domain works.  A team of lawyers wrote CC0.  Unlicense, which appears to borrow one paragraph/idea from CC0 and inappropriately merges it into the MIT license, is unvetted language and should not be used for any real software products.

The CC0 license in Gogs should have a caveat applied to it that says something like, "While the idea of a public domain license for software sounds good, making one that is recognized as valid globally is actually fraught with legal difficulties.  The MIT license is currently the closest to the public domain that someone can get for software while protecting the software developer from harm."  Doing that would leave a valid license in Gogs for people writing documentation who want public domain-style attribution (CC0) while pushing developers to use MIT instead of an inappropriate software license that doesn't properly protect them.
