### ISSUE TITLE
Encrypt LDAP Bind DN Credentials

### ISSUE THREAD

**Issue by danieldjewell** [gogs/gogs#5025]
- Gogs version (or commit ref): 0.11.34.1122
- Git version: 2.11.0
- Operating system: Debian 9.3 "stretch" 
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
  - [X] MariaDB 10.2 
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [X] Not relevant
- Log gist (usually found in `log/gogs.log`): N/A

## Description

The logon credentials for an LDAP BindDN are not encrypted. (Indeed, the system indicates that they are stored unencrypted.) The app.ini config already has a space for a configuration key (SECRET_KEY). This could be used to encrypt the credentials using a two-way encryption algorithm (because, of course, you'd have to be able to decrypt in order to login). 

A better overall solution, I feel, would be the one proposed in Issue https://github.com/gogits/gogs/issues/4884 -- using the user's credentials to actually login to the directory server would be far more preferable than the current method. That way, no credentials would be required at all. 

Related issues: 
* https://github.com/gogits/gogs/issues/4884

**Comment by zwets** [comment]
@unknwon this issue can be closed: the "direct bind" authenticator does precisely this: bind to the directory server with the user's credentials. All the BindDN authenticator does is to add an extra safeguard, namely to first check that the user object exists in the LDAP. 

However, both authenticators eventually perform the user bind. 

This also means that if your LDAP allows anonymous queries (as e.g. IdM / FreeIPA does), you can have the best of both worlds: use the BindDN authenticator but leave username and password empty.

The additional extra that the Bind DN authenticator offers is that it can be told (by ticking "Fetch attributes in Bind DN context") to retrieve the user attributes while bound as the Bind DN rather than as the user DN.
  
In sum: you only need the special Bind DN if (a) your LDAP does not allow anonymous queries but  you insist on doing the user object search before the user bind attempt, (b) your LDAP does not allow bound users to retrieve their own attributes (and you want to auto-import them), (c) your LDAP does not allow bound users to perform the group filter query.   

See also https://github.com/gogs/gogs/issues/4884#issuecomment-532180360

**Comment by unknwon** [comment]
Thanks @zwets, closing.
