### ISSUE TITLE
Unable to access a repository I created on try.gogs.io

### ISSUE THREAD

**Issue by Sauermann** [gogs/gogs#5440]
- Gogs version (or commit ref): 0.11.66.0916
- Can you reproduce the bug at https://try.gogs.io:
  - [ X ] Yes. Only there

## Description

After logging into my account "mark" on https://try.gogs.io I am unable to access the repository https://try.gogs.io/mark/test2 which I have created some time ago.
Instead I receive a 500 error.
I would have expected, that I am able to access the repository.

I can not reproduce this issue on my local gogs installation.

**Comment by Unknwon** [comment]
Hi,

I see that you have two repositories created over 3 years ago.

![image](https://user-images.githubusercontent.com/2946214/46046956-0c406c00-c0f1-11e8-82db-d746af3e0abb.png)

Demo site has been migrated between multiple servers since first launch, it is possible some files are missing for small number of repositories.

I can help you delete these two repositories in the admin panel if you would like to.

**Comment by Sauermann** [comment]
> I can help you delete these two repositories in the admin panel if you would like to.

Yes, that would be great. Thanks in advance.

**Comment by Unknwon** [comment]
Done :wink:

**Comment by Sauermann** [comment]
Thanks for your fast support!
