### ISSUE TITLE
Remote command execution

### ISSUE THREAD

**Issue by 5alt** [gogs/gogs#5469]
- Gogs version (or commit ref): newest(https://github.com/gogs/gogs/commit/3a4c981e3167875a3b60d0cee00ee85272608439)
- Can you reproduce the bug at https://try.gogs.io:
  - [ x] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant

## Description

I can login to arbitrary account. And when I logged in as admin, I can execute any command by git hooks.

I just tried login to Unknown's account but do not perform command execution.

<img width="1008" alt="gogs_admin_en" src="https://user-images.githubusercontent.com/8509449/47282860-601c7300-d613-11e8-8577-782b8a1653ff.png">

<img width="1015" alt="gogs_admin4_en" src="https://user-images.githubusercontent.com/8509449/47282887-71657f80-d613-11e8-8196-e8a183de1e18.png">

As this is a very severe issue, I won't post details here.

@Unknwon can you give me your email address and I send the details to you?

**Comment by UnicornCodes** [comment]
This is a very serious issue @Unknwon and this is the email u@gogs.io @5alt

**Comment by Unknwon** [comment]
Patch has pushed to fix this issue, please test on `develop` branch or https://try.gogs.io.

**Comment by 5alt** [comment]
hi, the patch can be bypassed using `..\` in Windows. You should check `..` actually.
```
if strings.ContainsAny(sid, "..") {
		return nil, errors.New("invalid 'sid': " + sid)
	}
```

**Comment by Unknwon** [comment]
`strings.ContainsAny` checks any substring of second argument, so even "..\\" should work:

https://play.golang.org/p/z2QN4ReKbfT

**Comment by 5alt** [comment]
> `strings.ContainsAny` checks any substring of second argument, so even "..\" should work:
> 
> https://play.golang.org/p/z2QN4ReKbfT

In your patch, you checked `./`, but forget to check `.\`
```
func (m *Manager) Read(sid string) (RawStore, error) {
	// No slashes or dots "./" should ever occur in the sid and to prevent session file forgery bug.
	// See https://github.com/gogs/gogs/issues/5469
	if strings.ContainsAny(sid, "./") {
		return nil, errors.New("invalid 'sid': " + sid)
	}

	return m.provider.Read(sid)
}
```

If gogs runs on Windows, `..\` can be still used for directory traversal attack.

so check `..` is the best solution

**Comment by Unknwon** [comment]
`strings.ContainsAny(sid, "./")` is equivalent to `strings.Contains(sid, ".") || strings.Contains(sid, "/")`.Thus as long as the sid contains ".", it returns true.

**Comment by zeripath** [comment]
Hmm. I think you're fixing things at the wrong level here. The issue is with the file session provider in file.go not necessarily the session.go.

Each session provider should be responsible for checking whether a session id is valid for it - therefore a check where the session id is valid should be in the Exists function of each of the providers.

For example, you may want to ensure that session IDs are a certain length on a database. Similarly if you're on ntfs and fat32 a session id with the path can't be more than 256 characters long due to filesystem constraints.

If there are global session id validity rules you need to check them before calling m.provider.Exists. As it stands the Exists if called before these are checked in Read - I'm not sure there's anything horrible you can do with just checking if a file exists but I'm fairly sure you shouldn't be able to do that.

**Comment by zeripath** [comment]
Looking again at this the "Destory" (is this meant to be destroy?) and Running methods basically allow arbitrary file creation and deletion through a similar fault. I'm not sure if these methods are available to end users to call arbitrarily but they almost certainly need checks placed on them too.
