### ISSUE TITLE
Unlisted repositories

### ISSUE THREAD

**Issue by marcinkunert** [gogs/gogs#5733]
I would love a possibility to create unlisted repositories.

It should work exactly like a public repository, but it shouldn't be visible on any listings (like private repositories are). The only way to reach it would be to get a link from the owner (or guess / brute-force it). So basically similar to YouTube unlisted videos.

I've searched for such functionality on github/bitbucket/gitlab but it doesn't seem to be available.

I'm creating programming tasks for my students and want to provide solutions as git repositories. If I use public repositories they can easily search for solutions for future exercises. Private repositories require me to add them one-by-one to have read access.

I've seen 2 closed issues (#2230, #4095) about this, I hope the reason they was closed was lack of explanation.

**Comment by achilleas-k** [comment]
We have this feature in our fork (@G-Node) which we run as a data hosting service (gin.g-node.org).  I opened a discussion a few weeks ago about getting some of our features into upstream (https://discuss.gogs.io/t/contributing-new-features-from-fork/2645) and this was one of them.

Since Unknwon agreed, I've been planning to clean up our implementation and open a PR, but that's still in the works.

**Comment by marcinkunert** [comment]
Hey @achilleas-k ! Any progress on the PR?

**Comment by achilleas-k** [comment]
Thanks for the reminder.  This task got lost in a lot of other higher priority stuff, but I'll move it up.

**Comment by achilleas-k** [comment]
I've been prototyping this a bit today and while I have some opinions and preferences about how this should work exactly, I think it might be best to discuss some of the details (especially if @unknwon has a preference on any of the choices).

## DB
On the DB/ORM side, I'm undecided about whether this should be a separate column/field (`IsUnlisted`), that works in a similar way to the private flag.  The alternative, which I think might be more elegant, would be to remove `IsPrivate` and replace it with a `Visibility` field that can have 3 states: Private, Unlisted, Public.
I find the latter more elegant, but I'm unsure how the database migration would work if a field is changed entirely instead of simply adding an extra one.

## UI
The decision above might also influence the way it's shown in the settings: Should it be two separate checkboxes, or a radio (or dropdown list) with 3 options?  Having two separate checkboxes can be confusing, since Private supersedes Unlisted and once Private is enabled, the Unlisted setting becomes irrelevant.  So for this, I'd definitely do it with a 3-state radio button, unless someone has an objection.

## Behaviour
This is how I imagine the behaviour of the setting.  I've started designing it this way, but I can make changes before finalising if anyone wants to discuss or object.

In general, an Unlisted repository behaves like a Private repository in search results, profile pages, organisation pages, and activity streams.  More specifically, a repository that is not private but marked as **Unlisted**:
- Appears in search results for the owner and for collaborators.
- Does not appear in search results for others users (not owner and not collaborator).
- Appears on the user's profile page for the owner and for collaborators.
- Does not appear on the user's profile page for other users.
- Does not appear in the user's public activity stream.
- Appears on Organisation pages for Org owners and team members with access.
- Does not appear on Organisation pages for non-members.
- Is accessible by everyone that knows the URL.

**Comment by unknwon** [comment]
@achilleas-k Thanks for the excellent details!

I think we need to first define what is "unlisted". To me, it just should be not listed in "list views", basically what you described in **Behaviour** section (though maybe not all of them would make sense right now but mostly).

Based on that, I believe it is an additional attribute of a repository and independent of repository's visibility (though private could invalidate the practice purpose but still valid in terms of implementation). Especially if we're going to extend visibility to not just "private" and "public", but also organizational, internal, etc.

WDYT?

**Comment by achilleas-k** [comment]
In the [`unlisted-repositories` branch](https://github.com/achilleas-k/gogs/tree/unlisted-repositories) in my fork I took a stab at both ways, first by adding an `unlisted` column and then by instead having a `visibility` column with 3 potential values.

I think internally both ways take similar amounts of work.  For instance, we can go through all the views and every private/public check in the codebase and add an extra check to treat unlisted repos as private in listings and as public when viewing the repo page and when cloning.  We could even go further and unify the checks with some easy-to-read functions that calculate whether a given user can view a given repo in a public listing and another for reading/cloning the repo directly.  This might probably be good for future changes as well (for example if you ever want to add fine-grained visibility controls).  I'd advocate for this approach especially if we decide to add the extra attribute instead of changing to a visibility "enum" attribute.  To clarify, if we have just one visibility attribute with multiple values, it makes localised checks easier, for example:

```go
repo.Visibility != REPO_PRIVATE  // can clone
repo.Visibility == REPO_PUBLIC   // can see in listing

opts.Visibility != repo.Visibility  // visibility changed
```

whereas if we just add the extra attribute, we get into situations where we need to check
```go
!(repo.IsPrivate || repo.IsUnlisted)  // can see in listing
!repo.IsPrivate  // can clone

opts.IsPrivate != repo.IsPrivate || opts.IsUnlisted != repo.IsUnlisted  // visibility changed
```
and that just seems a bit ugly to me and prone to errors.


In the end though I'm more interested in the UI aspect of the problem.  If we end up with the extra `unlisted` attribute, I think having two checkboxes, one for "Private" and one for "Unlisted" isn't great.  It shows the user two binary checkboxes which implies 4 combinations, but only 3 are valid.  So we have the following options:

1. Radio button with three choices
    - Good for readability, reflects the number of valid states.
    - Bad for reflecting internals: switching one option can have an effect on two columns; also the decision for which option to enable when loading the page gets tricky.
2. Two plain checkboxes
    - Good for reflecting internals.
    - Bad because it allows the user to toggle an option that may or may not have no effect: When Private is enabled, Unlisted is _irrelevant_.
3. Two checkboxes, but Unlisted is automatically _checked_ when Private is enabled.
    - Good for keeping the options consistent and valid.
    - Maybe bad for visual clutter, but not terrible.

In the third case, it would be "impossible" for a user to set Private On and Unlisted Off, but we would still have to check for it internally.

I realise I might be overthinking this.  Sorry for the long comment, I'm just thinking out loud in an effort to make the best decision, but I realise that I'm probably bikeshedding right now.

**Comment by unknwon** [comment]
Thanks for putting thinking into this problem!

A repository can be both private and unlisted, and forget about private, it is in fact "visibility + unlisted".

**Comment by achilleas-k** [comment]
> A repository can be both private and unlisted

What would the unlisted option change when a repository is already private?  I might be thinking about this differently, so I think it would be good to clarify.

> and forget about private, it is in fact "visibility + unlisted".

I understand the option on the repository settings page is called "Visibility", but I'm generally referring to the `db.Repository.IsPrivate` field or the underlying database `is_private` column when I talk about a repository being private.

**Comment by unknwon** [comment]
The database column is just implementation detail. It is a Boolean just because we only have private and public as visibility. It will be an enumeration in the future if we also have organizational, internal, etc.

**Comment by achilleas-k** [comment]
So how do you imagine `unlisted`?  Would it be separate from the visibility?  Might be good to know what you're imagining for the future of visibility.

**Comment by unknwon** [comment]
I'm kinda lost what is core thing we're discussing here... I thought I've said "Based on that, I believe it is an additional attribute of a repository and independent of repository's visibility", in other words, another field, i.e. `repository.is_listed`. And future visibilities are _organizational, internal, etc._.

**Comment by achilleas-k** [comment]
I thought perhaps that, since you also said
> It will be an enumeration in the future if we also have organizational, internal, etc.

now would be a good time to switch to an enumeration in preparation for future changes.  Or even better, perhaps we could define those future changes and include them in this change.

I also wanted to get your thoughts on the UI details, which necessarily have to be included in this change.  My long comments and thoughts are an attempt to settle on details beforehand so we don't get long back-and-forth changes in PRs with extra work.

I understand now.  I'll just work on unlisted as a separate attribute for now and we can take it from there.

**Comment by unknwon** [comment]
> now would be a good time to switch to an enumeration in preparation for future changes. Or even better, perhaps we could define those future changes and include them in this change.

Do one thing at a time, smaller PRs are easier to get reviewed and merged :)

**Comment by achilleas-k** [comment]
Little update on this: It's basically done, with a few caveats.  I want to test all the combinations before opening the PR (probably tomorrow).  I'll include screenshots for settings for review.

One minor detail I'd like some feedback on is regarding the repository icon for unlisted repositories.  I think it makes sense to show the user when a repo is unlisted (much like the padlock shows when it's private), but there's no appropriate octicon for it (I've been using the [eye](https://primer.style/octicons/eye) icon for testing, but that's not a good choice).  The [eye-closed](https://primer.style/octicons/eye-closed) icon would be good, but it's not included in Octicons 4.3.0, which is what's in Gogs now.  Would you update the assets for this or would you prefer another icon (or none) be used?

**Comment by unknwon** [comment]
> The [eye-closed](https://primer.style/octicons/eye-closed) icon would be good, but it's not included in Octicons 4.3.0, which is what's in Gogs now. Would you update the assets for this or would you prefer another icon (or none) be used?

I've always been wanted to upgrade Octicons to the latest. But 4.3.0 seems the last version they release font format. Right now they use SVG and it takes extra effort to update all places in Gogs (PR welcome!).

**Comment by achilleas-k** [comment]
Interesting.  I'll have a look.

**Comment by achilleas-k** [comment]
Opened a separate issue for the octicons upgrade discussion.

**Comment by unknwon** [comment]
Huge thanks to @achilleas-k, it is now supported!
