### ISSUE TITLE
Random 500 error

### ISSUE THREAD

**Issue by Ulyev-ad** [gogs/gogs#5742]
Centos7 x64 operating system. Version of gogs 0.11.86.0130. Installed on MySql 5.5.60-MariaDB. Absolutely by chance there is a 500 error, and when you re-update the page everything works. Git version 1.8.3.1

Managed to catch 500 error, in logs I see it: **2019/07/09 22:25:46 [ERROR] [...g/context/context.go:191 ServerError()] SearchRepositoryByName: Count: invalid connection**

![image](https://user-images.githubusercontent.com/13260152/60917589-fecc2b00-a299-11e9-942f-ea209a703870.png)

I start through systemd
```
[Unit]
Description=Gogs
After=syslog.target
After=network.target
After=mariadb.service mysqld.service postgresql.service memcached.service redis.service

[Service]
# Modify these two values and uncomment them if you have
# repos with lots of files and get an HTTP error 500 because
# of that
###
#LimitMEMLOCK=infinity
#LimitNOFILE=65535
Type=simple
User=root
Group=root
WorkingDirectory=/gogs
ExecStart=/gogs/gogs web
Restart=always
Environment=USER=root HOME=/

# Some distributions may not support these hardening directives. If you cannot start the service due
# to an unknown option, comment out the ones not supported by your version of systemd.
ProtectSystem=full
PrivateDevices=yes
PrivateTmp=yes
NoNewPrivileges=true

[Install]
WantedBy=multi-user.target
```

**Comment by Ulyev-ad** [comment]
Updated git to version 2.16.5, the problem remained. Found in other projects that the problem may be related to the database connection. But other projects (for Vesta server) mysql is stable.

**Comment by MohammedFadin** [comment]
I'm actually facing the same issue with the latest Gogs docker

**Comment by unknwon** [comment]
Hi, I notice the MySQL version you're using is below required version (5.7) according to https://gogs.io/docs/installation. The MySQL driver Gogs uses may have bad support on older versions of MySQL.

I think this issue is basically the same as https://github.com/gogs/gogs/issues/5532.

Gogs has made best effort to avoid this kind of errors:
https://github.com/gogs/gogs/blob/c154721f4a8f3e24d2f6fb61e74b4b64529255c2/models/models.go#L204-L207

You may also want to double check you MySQL IDLE and/or max life time settings.
