### ISSUE TITLE
Adding two empty dummy files, repeats the same file twice in UI.

### ISSUE THREAD

**Issue by chill1n** [gogs/gogs#6235]
Application version: 0.12.0+dev
Git version: 2.24.3
Go version: go1.14.6
Build time: 2020-07-17 02:57:14 UTC
Build commit: 90904b3f420d41cf56c62b6d96234b199399f3e4

OS: Ubuntu 20.04
DB:  Sqlite

Issue: Adding (at least) two empty dummy files, repeats the same file twice in UI.

1. Create an empty repository in the UI
2. Clone the repo
2. Create two empty files in this repo, e.g. dummy.php and dummy.py
3. Add the files, commit, and push
4. Go to the UI and see that dummy.php is shown twice

Reproduced at try.gogs.io

Expected behavior:
All original file names shown in UI without duplicates.

Actual behavior:
Duplicate file names shown.

**Comment by manfer** [comment]
The problem is on git-module

https://github.com/gogs/git-module/blob/cf0a6d71b880c42c4dd507b59be762c5a05c649a/tree_entry.go#L261-L270

```go
	infos := make(map[[20]byte]*EntryCommitInfo, len(es))
	for info := range results {
		infos[info.Entry.id.bytes] = info
	}


	commitsInfo := make([]*EntryCommitInfo, len(es))
	for i, e := range es {
		commitsInfo[i] = infos[e.id.bytes]
	}
	return commitsInfo, nil
```

An entry id is not unique so it should not be used as map key. When on a tree there is a file or folder with same contents its SHA1 hash is equal. This can be tested in any repo with two files with same content executing `git ls-tree HEAD`

Maybe a solution is using name as the key as I bet entity name is unique in any tree.

```go
	infos := make(map[string]*EntryCommitInfo, len(es))
	for info := range results {
		infos[info.Entry.name] = info
	}


	commitsInfo := make([]*EntryCommitInfo, len(es))
	for i, e := range es {
		commitsInfo[i] = infos[e.name]
	}
	return commitsInfo, nil
```

Or maybe just including entity index on info so later only one loop is needed to fill commitsInfo.

```go

// EntryCommitInfo contains a tree entry with its commit information.
type EntryCommitInfo struct {
	Entry     *TreeEntry
        Index     int
	Commit    *Commit
	Submodule *Submodule
}

        ...
			go func(e *TreeEntry, i int) {
				defer func() {
					wg.Done()
        ...

				info := &EntryCommitInfo{
					Entry: e,
                                        Index: i,
				}

        ...

				results <- info
			}(e, i)
		}
	}()

        ...

	commitsInfo := make([]*EntryCommitInfo, len(es))
	for info := range results {
		commitsInfo[info.Index] = info
	}
	return commitsInfo, nil
```

**Comment by manfer** [comment]
https://github.com/gogs/gogs/issues/6186
