### ISSUE TITLE
postgresql: Failed to initialize ORM engine

### ISSUE THREAD

**Issue by evdenis** [gogs/gogs#6286]
Gogs fails to connect to psql after an update. Manual connection works as expected.

```
2020/08/27 16:26:10 [FATAL] [...t/gogs/internal/route/install.go:75 GlobalInit()] Failed to initialize ORM engine: open database: pq: password authentication failed for user "git"
```

```
$ psql --version
psql (PostgreSQL) 11.7 (Debian 11.7-0+deb10u1)
$ cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 10 (buster)"
...
$ apt list --installed | grep gogs
gogs/unknown,now 0.11.91-1598527633.016d9d8c.buster amd64 [installed]

#According to the /opt/gogs/CHANGELOG.md installed version is:
#0.13.0+dev
```

**Comment by unknwon** [comment]
Hi, I think it is because 0.13.0+dev stops reading old config option for password (`PASSWD` -> `PASSWORD`), see https://github.com/gogs/gogs/issues/6276#issuecomment-678787224. 

Related: https://github.com/gogs/gogs/issues/6282?notification_referrer_id=MDE4Ok5vdGlmaWNhdGlvblRocmVhZDEwOTk5NTQ1MzE6Mjk0NjIxNA%3D%3D&notifications_query=repo%3Agogs%2Fgogs%20is%3Aunread
