### ISSUE TITLE
[Q] where is templates directory?

### ISSUE THREAD

**Issue by dehghani-mehdi** [gogs/gogs#6452]
I didn't find any related info in change log, nor docs.

Did you embed the template and static files into exe? I can not find any of them.

When I install the latest version only following folders generated for me, which is not what I expected.

`data, log, scripts`

**Comment by jucelin** [comment]
we should create folders by ourselves. doc: https://gogs.io/docs/features/custom_template
![example](https://user-images.githubusercontent.com/4074034/102288730-0e17d380-3f78-11eb-91d6-fe02475be078.png)

**Comment by billthefarmer** [comment]
The change in version 0.12.0 embedding assets, #5920, renders the docs page [Customizing templates](https://gogs.io/docs/features/custom_template) invalid. I tested the config option `[server] LOAD_ASSETS_FROM_DISK = true`, which of course doesn't work because there are no assets to load from disk, unless there is another option to write them out to disk that I haven't found. The only source for the templates that I have found is here, from the sources.

Please keep the docs up to date with major changes such as this. Another excellent project which I use using Go is Hugo, which seems to be able to manage this most of the time.

**Comment by dehghani-mehdi** [comment]
Never mind, I'm using Gitea now.
